// ---------------------------------------------------------------------------
// P2-B voice pack: lightweight async clip player for the 5 cheerleader clips.
//
// Design constraints (P2-B brief, tech-p2.md §2):
//   - M5.Speaker is already online in firmware (existing completion tone proves
//     this). We add an int16_t PCM path through M5Unified's Speaker_Class which
//     exposes playRaw(const int16_t*, size_t, sample_rate, ...) directly (see
//     upstream Speaker_Class.hpp — confirmed via upstream source, the
//     "playRaw(const int16_t* raw_data, ...)" overload).
//   - Single-channel mutex: a new playClip() interrupts any in-progress clip
//     so the device never queues stale "好哒,通过~" on top of a fresh "不行哦".
//   - Volume is bounded by a settable ceiling (default 192/255 ≈75%) to honor
//     PRD NFR1 (clipped audio) and NFR3 (battery).
//   - clip data lives in audio_clips_data.h, generated by
//     tools/gen_placeholder_wav.py + tools/wav_to_header.py from the WAVs in
//     firmware/assets/audio/.
//
// The .cpp intentionally does NOT include <M5Unified.h> directly — instead we
// forward-declare M5.Speaker and the playRaw/setVolume/stop/isPlaying overloads
// that we use. That keeps the validation command
//   g++ -fsyntax-only -std=c++17 -I src src/audio_clips.cpp
// self-contained on a VM that has no PlatformIO/M5Unified install. The real
// firmware pulls in board_compat.h which already #includes <M5Unified.h>, and
// the linker resolves the Speaker methods at full build time on the user's box.
// ---------------------------------------------------------------------------
#pragma once

#include <stdint.h>
#include <stddef.h>

enum class Clip : uint8_t {
  Approve = 0,  // "好哒，通过~"
  Deny    = 1,  // "不行哦，再检查一遍嘛~"
  Error   = 2,  // "加油哦，bug 是成长的营养~"
  Idle1   = 3,  // "记得喝水哦"
  Idle2   = 4,  // "你今天也很努力呢"
  Boot    = 5,  // "我来陪你写代码啦~"
  Count   = 6,
};

constexpr uint8_t CLIP_DEFAULT_MAX_VOLUME = 192;  // 192/255 ≈ 75% (PRD NFR1/3)

// Sample rate of the bundled PCM data. keep in sync with audio_clips_data.h
// generator (16 kHz mono) — the firmware passes this directly to Speaker.playRaw.
constexpr uint32_t CLIP_SAMPLE_RATE_HZ = 16000;

// Initialize the player. maxVolume is the upper bound the user cannot exceed
// (PRD §FR1: "音量上限默认 75% (供电保护)"). Safe to call once from setup().
void audioClipsInit(uint8_t maxVolume = CLIP_DEFAULT_MAX_VOLUME);

// Async non-blocking play. New clips cancel any currently-playing clip so the
// device never queues stale audio (NFR1: "起播 < 500ms"). No-op if the
// requested Clip index is out of range or the sample buffer is missing.
void playClip(Clip c);

// True iff the Speaker has at least one channel occupied. Cheap; safe to poll
// every loop iteration (the implementation forwards to Speaker.isPlaying()).
bool clipPlaying();

// Current applied volume (0..maxVolume). Persisted in NVS by the caller.
uint8_t clipVolume();
void setClipVolume(uint8_t v);  // clamped to [0, maxVolume]
